spring:
  config:
    activate:
      on-profile: default
  boot:
    admin:
      client:
        url: http://localhost:8080
  security:
    user:
      name: user
      password: user
---
spring:
  config:
    activate:
      on-profile: dev